# yaml-language-server: $schema=https://unpkg.com/@sveltia/cms/schema/sveltia-cms.json

backend:
  name: github
  repo: 108adams/adamkucharczyk.pl

media_folder: src/assets/images/uploads
public_folder: /assets/images/uploads

collections:
  - name: posts
    label: Posts
    label_singular: Post
    folder: src/posts
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Date, name: date, widget: datetime, date_format: YYYY-MM-DD, time_format: false }
      - { label: Description, name: description, widget: string }
      - label: Discover
        name: discover
        widget: object
        fields:
          - { label: Description, name: description, widget: string }
      - { label: Body, name: body, widget: markdown }
